#**Data Gathering**
Data gathering is the process of collecting raw data from various reliable sources to answer specific questions and support analysis.

# **Import**

Data can be imported from multiple sources such as CSV, Excel, text files, JSON files, databases (SQL/NoSQL), as well as through APIs and web scraping techniques.

*   from CSV
*   from EXCEL
*   from TEXT
*   from JSON
*   from SQL

## **Import Data from CSV**

In [2]:
import pandas as pd

### **Opening a local csv file**

In [68]:
df = pd.read_csv('/content/aug_train.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### **opening a csv file from a url**

In [69]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

### **Step Parameter**

Defines the delimiter used to separate values in a CSV file (e.g., comma, tab, semicolon).

tsv ko load karne me kaam ata, sep ki default value ',' hoti tu in case of tsv hamein sep='\t' karna parega..

In [70]:
#step -> names parameter

df = pd.read_csv('/content/movie_titles_metadata.tsv', sep='\t', names = ['s_no', 'name', 'year', 'rating', 'votes', 'genre'])
df

,s_no,name,year,rating,votes,genre
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

### **index_col parameter**

In [71]:
df = pd.read_csv('/content/aug_train.csv', index_col = 'enrollee_id')
df

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### **Header Parameter**

In [72]:
df = pd.read_csv('test.csv', header=1)
df

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

### **usecols parameter**

jo jo columns chahiye sirf wohi load honge baqi hat jaenge

In [73]:
pd.read_csv('aug_train.csv', usecols=['enrollee_id','gender', 'education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

### **Skiprows / nrows Parameter**

In [74]:
pd.read_csv('aug_train.csv', skiprows=[0,2]) #nrows=100

,8949,city_103,0.92,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,Unnamed: 9,Unnamed: 10,1,36,1.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### **Encoding Parameter**

In [75]:
pd.read_csv('zomato.csv', encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

### **Skip bad lines**

In [76]:
pd.read_csv('BX-Books.csv',sep=';',encoding='latin-1',on_bad_lines='skip') #jis row me koi masla hoga wo skip hojaegi

/tmp/ipython-input-1527021019.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('BX-Books.csv',sep=';',encoding='latin-1',on_bad_lines='skip') #jis row me koi masla hoga wo skip hojaegi

,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
1,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
2,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
3,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
4,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
...,...,...,...,...,...,...,...,...
271354,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271355,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271356,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271357,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271358,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

### **dtypes Parameter**

In [77]:
pd.read_csv('aug_train.csv', dtype = {'target':int}) #is dataset ke last col me 0 aur 1 hai bas but dtype float hai, int me change kar sakte isko

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0

### **Handling Dates**

In [78]:
pd.read_csv('IPL Matches 2008-2020.csv', parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

### **Convertors**

In [79]:
def rename(name):
  if name == "Royal Challengers Bangalore":
    return "RCB"
  else:
    return name

In [80]:
rename("Royal Challengers Bangalore")

'RCB'

In [81]:
pd.read_csv('IPL Matches 2008-2020.csv', converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

### **na_values**

In [82]:
pd.read_csv('aug_train.csv', na_values=['-'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### **Loading a Huge Datasets in chunks**

In [83]:
df = pd.read_csv('aug_train.csv', chunksize=5000)

In [84]:
for chunk in df:
  print(chunk.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

## **Import Data from EXCEL**

In [85]:
pd.read_excel('Output.xlsx', index_col='emp_id')

                 name department  gender  experience_years
emp_id
E001    Shayan Afridi         IT    Male                 2
E002       Sara Ahmed         HR  Female                 4
E003       Usman Raza    Finance    Male                 3
E004      Ayesha Noor         IT  Female                 1
E005        Hamza Ali  Marketing    Male                 5

In [86]:
pd.read_excel('Output.xlsx',index_col='emp_id', sheet_name='Sheet2')

,tasks_assigned,tasks_completed,attendance_percentage,performance_score
emp_id,,,,
E001,20,18,90,82
E002,25,23,95,88
E003,22,19,85,78
E004,18,15,80,70
E005,30,28,97,92

## **Import Data from TEXT**

In [87]:
pd.read_csv('sample.txt', index_col='emp_id')  #agar tab separated values hoti tu sep='\t' kar dete

               name department  gender  experience_years
emp_id
E001       Ali Khan         IT    Male                 2
E002     Sara Ahmed         HR  Female                 4
E003     Usman Raza    Finance    Male                 3
E004    Ayesha Noor         IT  Female                 1
E005      Hamza Ali  Marketing    Male                 5

## **Import Data from JSON**

In [88]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [89]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.0405
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.6910
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.8970
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,4.1600
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,2.6300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.1770
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.2050
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-19,1771459202,0.2820

## **Import Data from SQL**

In [117]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /usr/local/lib/python3.12/dist-packages (2.2.9)

In [118]:
import mysql.connector

In [119]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (111 Connection refused)

In [ ]:
pd.read_sql_query("select * from city", conn)

# **Export**
*   to CSV
*   to EXCEL
*   to HTML
*   to JSON
*   to SQL

## **Export Data to CSV**

In [94]:
import pandas as pd

In [96]:
df = pd.read_csv('deliveries.csv')

In [97]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [98]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()

In [99]:
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [100]:
temp_df.to_csv('batsman_run.csv', index=False)

In [101]:
piv = df.pivot_table(index='batsman',columns='bowling_team',values='batsman_runs',aggfunc='sum')
piv.head()

bowling_team,Chennai Super Kings,Deccan Chargers,Delhi Capitals,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
batsman,,,,,,,,,,,,,,,
A Ashish Reddy,45.0,NaN,NaN,36.0,NaN,37.0,NaN,17.0,27.0,26.0,37.0,NaN,NaN,55.0,NaN
A Chandila,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
A Chopra,NaN,35.0,NaN,13.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
A Choudhary,NaN,NaN,NaN,NaN,15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
A Dananjaya,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
piv.to_csv('batsman_vs_team.csv')

## **Export Data to EXCEL**

In [103]:
df.sample()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
29487,127,2,Kings XI Punjab,Royal Challengers Bangalore,12,5,RS Bopara,KC Sangakkara,JD Ryder,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [104]:
temp_df = df.groupby('batsman')['batsman_runs'].sum()
temp_df.head()

batsman
A Ashish Reddy    280
A Chandila          4
A Chopra           53
A Choudhary        25
A Dananjaya         4
Name: batsman_runs, dtype: int64

In [105]:
temp_df.to_excel('batsman_runs.xlsx')

In [106]:
temp_df2 = df.pivot_table(index='batsman',columns='bowling_team',values='batsman_runs',aggfunc='sum')

In [107]:
with pd.ExcelWriter('testexcel.xlsx') as writer:
  temp_df.to_excel(writer, sheet_name='batsman_runs')
  temp_df2.to_excel(writer, sheet_name='batsman_vs_team')

## **Export Data to HTML**

In [108]:
df.sample()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
79365,337,1,Deccan Chargers,Kolkata Knight Riders,5,6,S Dhawan,KC Sangakkara,SP Narine,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [109]:
temp_df = df.query('batsman_runs == 6').pivot_table(index='over', columns='ball', values='batsman_runs', aggfunc='count')
temp_df.head()

ball     1     2     3     4     5     6     7    8    9
over
1      7.0  12.0  27.0  31.0  24.0  20.0  12.0  1.0  NaN
2     26.0  30.0  35.0  43.0  45.0  42.0  10.0  5.0  NaN
3     63.0  46.0  57.0  52.0  48.0  58.0   8.0  2.0  1.0
4     49.0  61.0  51.0  81.0  54.0  53.0  11.0  1.0  NaN
5     54.0  56.0  82.0  64.0  62.0  60.0  10.0  2.0  NaN

In [110]:
temp_df.to_html('sixes_heatmap.html')

## **Export Data to JSON**

In [111]:
df.sample()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
117755,497,1,Mumbai Indians,Kolkata Knight Riders,12,1,AT Rayudu,RG Sharma,PP Chawla,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [112]:
df.groupby(['batsman', 'batting_team'])['batsman_runs'].sum().unstack().to_json('ipl.json')

## **Export Data to SQL**

In [113]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 3.4 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [114]:
import pymysql
from sqlalchemy import create_engine

In [116]:
engine = create_engine("mysql+pymysql://root:@localhost/ipl")
# {root}:{password}@{url}/{database}
df.to_sql('ipl_delivery', con = engine, if_exists = 'append')

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

# **From API**
API (Application Programming Interface) is a set of rules and protocols that allows one software application to communicate and interact with another.

**Simple Definition:**

An API acts like a bridge between two programs, allowing them to request and exchange data.

In [1]:
import requests

In [5]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=fdb1f1e297b89ad579d40b04c08d04de&language=en-US&page=1")

In [20]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','overview','vote_average','vote_count']].head()

In [23]:
df = pd.DataFrame()

In [26]:
for i in range(1,429):
  response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=fdb1f1e297b89ad579d40b04c08d04de&language=en-US&page=1".format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','overview','vote_average','vote_count']]
  df = pd.concat([df,temp_df], ignore_index=True)

In [27]:
df

,id,title,release_date,popularity,overview,vote_average,vote_count
0,278,The Shawshank Redemption,1994-09-23,37.6026,Imprisoned in the 1940s for the double murder ...,8.715,29765
1,238,The Godfather,1972-03-14,47.3550,"Spanning the years 1945 to 1955, a chronicle o...",8.687,22477
2,240,The Godfather Part II,1974-12-20,18.1309,In the continuing saga of the Corleone crime f...,8.571,13598
3,424,Schindler's List,1993-12-15,16.4257,The true story of how businessman Oskar Schind...,8.567,17125
4,389,12 Angry Men,1957-04-10,11.3451,The defense and the prosecution have rested an...,8.556,9751
...,...,...,...,...,...,...,...
8555,13,Forrest Gump,1994-06-23,20.2034,A man with a low IQ has accomplished great thi...,8.462,29258
8556,769,GoodFellas,1990-09-12,21.7730,"The true story of Henry Hill, a half-Irish, ha...",8.452,14030
8557,346,Seven Samurai,1954-04-26,7.5062,A samurai answers a village's request for prot...,8.500,4113
8558,12477,Grave of the Fireflies,1988-04-16,0.0091,"In the final months of World War II, 14-year-o...",8.444,6363
8559,637,Life Is Beautiful,1997-12-20,9.1032,A touching story of an Italian book seller of ...,8.440,13797

In [28]:
df.to_csv('movies.csv')

# **Web Scraping**

**Web Scraping** is the process of automatically extracting data from websites using programs or scripts.

It allows us to collect information such as text, images, prices, or tables from web pages and store it in a structured format like CSV or a database.

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

### **If response 403 error occur**

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}

requests.get('url',headers=headers).text

In [3]:
webpage = requests.get("https://oladoc.com/pakistan/karachi/hospital").text  # with this we get the complete html souce code of the webpage

In [4]:
soup = BeautifulSoup(webpage, 'lxml')

In [5]:
# print(soup.prettify())

In [6]:
hospitals = soup.find_all('div', class_='card-body p-2 py-lg-3')    # har hospital ke div me ja rahe hain, phir loop laga kar individually sabka data nikalenge
len(hospitals)

20

In [36]:
name = []
address = []
contact = []
panel_drs = []
area = []
timings = []

for i in hospitals:

    # Hospital Name
    h2_tag = i.find('h2')
    name.append(h2_tag.text.strip() if h2_tag else None)

    # Address
    address_tag = i.find('small', class_='text-muted text-sm')
    address.append(address_tag.text.strip() if address_tag else None)

    # Contact
    phone_tag = i.find('a', id='call-tooltip-opner')
    if phone_tag and phone_tag.get('href'):
        contact.append(phone_tag['href'].replace('tel:', '').strip())
    else:
        contact.append(None)

    # Panel Doctors
    panel_tag = i.find('small', class_='col pl-0')
    panel_drs.append(panel_tag.text.strip() if panel_tag else None)

    # Area & Timings (same class — so use find_all)
    info_tags = i.find_all('small', class_='col pl-lg-0')

    if len(info_tags) >= 2:
      timings.append(info_tags[0].text.strip())
      area.append(info_tags[1].text.strip())
    else:
      area.append(None)
      timings.append(None)


# Create DataFrame
d = {
    "Hospital Name": name,
    "Address": address,
    "Contact": contact,
    "Panel Doctors": panel_drs,
    "Area": area,
    "Timings": timings
}

df = pd.DataFrame(d)

In [37]:
df

,Hospital Name,Address,Contact,Panel Doctors,Area,Timings
0,Taj Medical Complex (TMC),"Taj Medical Complex, Hamdard University Hospit...",02138140600,85 Panel Doctors,None,None
1,Anum Hospital,"Main Road, Pak Kauser Town, Khokhrapar 2, Mali...",02138140600,48 Panel Doctors,None,None
2,Karachi Medical Complex (Consultant Clinics),"Rae Ave, Block 16 Gulshan-e-Iqbal, Karachi",02138140600,52 Panel Doctors,"Gulshan-e-Iqbal, Karachi",Monday to Saturday: 9Am - 9PM
3,RIMS Trauma Hospital,"PECHS, Block 6 Extension, Karachi",02138140600,51 Panel Doctors,None,None
4,Al-Hujjat Medical & Diagnostics,"Ground Floor, Zahra Residency, Near Khurasan I...",02138140600,38 Panel Doctors,None,None
5,Altamash General Hospital,"St-9A, Block 1, Clifton, Karachi",021 38140600,29 Panel Doctors,None,None
6,Hill Park General Hospital (HPGH),"S.N.C.C. 3/4, Block-3, Shaheed-e-Millat Road, ...",02138140600,71 Panel Doctors,"Shaheed-e-Millat Road, Karachi",24 Hours Emergency
7,Taj Consultants Clinics,"C-15/1, Block 3, Gulshan Chowrangi, Rashid Min...",0213 8140 600,46 Panel Doctors,"Gulshan-e-Iqbal, Karachi",MON - SAT : 09:30 am - 10:30 pm
8,South City Hospital,"Street No. 1, Block 3, Shahrah-e-Firdousi, Cli...",02138140600,1 Recommendations,"Clifton, Karachi",24 Hours Emergency
9,Medicare Cardiac & General Hospital,"22-23 Shaheed-e-Millat Rd, Bihar Muslim Societ...",,54 Panel Doctors,None,None
10,LifeLine Hospital (North Nazimabad),"D-14, Block-B, North Nazimabad, Karachi",021 38140600,43 Panel Doctors,None,None
11,Hilal-e-Ahmar Medical Hospital,"Block 7, Teen Talwar Clifton, Karachi",0213 8140 600,41 Panel Doctors,None,None
12,Patel Hospital,"St #18, Block 4, Gulshan-e-Iqbal, Karachi",02138140600,1 Recommendations,None,None
13,Mamji Hospital,"C-19, Block-17, F.B Area, Karachi",02138140600,92 Panel Doctors,"Federal B Area, Karachi",24 Hour Emergency
14,Lyfe Healthcare,"Plot # 7&8. Hospital Building Main, Tipu Sulta...",02138183435,38 Panel Doctors,None,None
15,Gastro Liver Multispeciality Center and Endosc...,"Shop No. SC-14 & 19, Ground Floor, APWA Comple...",02138140600,22 Panel Doctors,None,None
16,Park Lane Hospital,"56 Shahra e Iran, Old Clifton, Opposite Briti...",None,78 Panel Doctors,None,None
17,Ibn-e-Seena Hospital (Karachi),"St-22-B, University Road, Block 6, Gulshan-e-I...",02138140600,105 Panel Doctors,None,None
18,Western Clinics,"29-C, Al Murtaza Commerical Lane 3, DHA Phase ...",02138140600,27 Panel Doctors,None,None
19,United Hospital,"Plot No. 16B, Al Riaz Society, Shaheed-e-Milat...",02138140600,20 Panel Doctors,None,None

In [8]:
name

['Taj Medical Complex (TMC)',
 'Anum Hospital',
 'Karachi Medical Complex (Consultant Clinics)',
 'RIMS Trauma Hospital',
 'Al-Hujjat Medical & Diagnostics',
 'Altamash General Hospital',
 'Hill Park General Hospital (HPGH)',
 'Taj Consultants Clinics',
 'South City Hospital',
 'Medicare Cardiac & General Hospital',
 'LifeLine Hospital (North Nazimabad)',
 'Hilal-e-Ahmar Medical Hospital',
 'Patel Hospital',
 'Mamji Hospital',
 'Lyfe Healthcare',
 'Gastro Liver Multispeciality Center and Endoscopy Services',
 'Park Lane Hospital',
 'Ibn-e-Seena Hospital (Karachi)',
 'Western Clinics',
 'United Hospital']

In [9]:
address

['Taj Medical Complex, Hamdard University Hospital, M.A Jinnah Road Opposite Capri Cinema, Karachi',
 'Main Road, Pak Kauser Town, Khokhrapar 2, Malir Extension, Karachi',
 'Rae Ave, Block 16 Gulshan-e-Iqbal, Karachi',
 'PECHS, Block 6 Extension, Karachi',
 'Ground Floor, Zahra Residency, Near Khurasan Imambargah ,Numaish, Karachi',
 'St-9A, Block 1, Clifton, Karachi',
 'S.N.C.C. 3/4, Block-3, Shaheed-e-Millat Road, Karachi',
 'C-15/1, Block 3, Gulshan Chowrangi, Rashid Minhas Road, Gulshan-e-Iqbal, Karachi.',
 'Street No. 1, Block 3, Shahrah-e-Firdousi, Clifton, Karachi',
 '22-23 Shaheed-e-Millat Rd, Bihar Muslim Society BMCHS Sharafabad.',
 'D-14, Block-B, North Nazimabad, Karachi',
 'Block 7, Teen Talwar Clifton, Karachi',
 'St #18, Block 4, Gulshan-e-Iqbal, Karachi',
 'C-19, Block-17, F.B Area, Karachi',
 'Plot # 7&8. Hospital Building Main, Tipu Sultan Road, Karachi,',
 'Shop No. SC-14 & 19, Ground Floor, APWA Complex, Aga Khan III Road (Garden Road), Opposite Ankleseria Hospital, Saddar, Karachi',
 '56 Shahra  e Iran, Old Clifton, Opposite British Deputy High Commission, Karachi',
 'St-22-B, University Road, Block 6, Gulshan-e-Iqbal, Karachi',
 '29-C, Al Murtaza Commerical Lane 3, DHA Phase 8, Karachi',
 'Plot No. 16B, Al Riaz Society, Shaheed-e-Milat Road, PECHS, Karachi']

In [10]:
contact

['02138140600',
 '02138140600',
 '02138140600',
 '02138140600',
 '02138140600',
 '021 38140600',
 '02138140600',
 '0213 8140 600',
 '02138140600',
 '',
 '021 38140600',
 '0213 8140 600',
 '02138140600',
 '02138140600',
 '02138183435',
 '02138140600',
 None,
 '02138140600',
 '02138140600',
 '02138140600']

## **get all pages data**

In [43]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0"
}

final = pd.DataFrame()

for page in range(0, 1470, 10):
    url = f"https://oladoc.com/pakistan/karachi/hospital/{page}"

    webpage = requests.get(url, headers=headers).text
    soup = BeautifulSoup(webpage, 'lxml')
    hospitals = soup.find_all('div', class_='card-body p-2 py-lg-3')

    name = []
    address = []
    contact = []
    panel_drs = []
    area = []
    timings = []

    for i in hospitals:

        h2_tag = i.find('h2')
        name.append(h2_tag.text.strip() if h2_tag else None)

        address_tag = i.find('small', class_='text-muted text-sm')
        address.append(address_tag.text.strip() if address_tag else None)

        phone_tag = i.find('a', id='call-tooltip-opner')
        if phone_tag and phone_tag.get('href'):
            contact.append(phone_tag['href'].replace('tel:', '').strip())
        else:
            contact.append(None)

        panel_tag = i.find('small', class_='col pl-0')
        panel_drs.append(panel_tag.text.strip() if panel_tag else None)

        info_tags = i.find_all('small', class_='col pl-lg-0')

        if len(info_tags) >= 2:
            area.append(info_tags[0].text.strip())
            timings.append(info_tags[1].text.strip())
        else:
            area.append(None)
            timings.append(None)

    df = pd.DataFrame({
        "Hospital Name": name,
        "Address": address,
        "Contact": contact,
        "Panel Doctors": panel_drs,
        "Area": area,
        "Timings": timings
    })

    final = pd.concat([final, df], ignore_index=True)

print("Total records:", len(final))

Total records: 2930

In [45]:
final

,Hospital Name,Address,Contact,Panel Doctors,Area,Timings
0,Taj Medical Complex (TMC),"Taj Medical Complex, Hamdard University Hospit...",02138140600,85 Panel Doctors,None,None
1,Anum Hospital,"Main Road, Pak Kauser Town, Khokhrapar 2, Mali...",02138140600,48 Panel Doctors,None,None
2,Karachi Medical Complex (Consultant Clinics),"Rae Ave, Block 16 Gulshan-e-Iqbal, Karachi",02138140600,52 Panel Doctors,Monday to Saturday: 9Am - 9PM,"Gulshan-e-Iqbal, Karachi"
3,RIMS Trauma Hospital,"PECHS, Block 6 Extension, Karachi",02138140600,51 Panel Doctors,None,None
4,Al-Hujjat Medical & Diagnostics,"Ground Floor, Zahra Residency, Near Khurasan I...",02138140600,38 Panel Doctors,None,None
...,...,...,...,...,...,...
2925,Hashmanis Hospital Laboratory (North Karachi),"ST-41/1, Sector 11-I, near Saleem Centre, Nort...",02138140600,None,None,None
2926,Urban Health Center,Malir City,,None,None,None
2927,Imam Basri Medical Memorial Hospital,"I.B. Soomro Ave, Ahsanabad # 2, Sector 9-A, Gu...",02138140600,None,None,None
2928,"Hashmanis Hospital, Tariq Road (Drive Thruough)","Delhi Mercantile Society PECHS, Karachi",021 38140600,None,None,None
2929,Al-Hafiz Clinics,"Shop # 03 BYJCHS Plot# 125 Near Alamgir Road, ...",,None,None,None

In [48]:
final.to_csv('Hospital_in_Karachi')